# Generated by Django 6.0.3 on 2026-04-20 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0002_cluster_prometheus_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('user', '普通用户')], default='user', max_length=16, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机号')),
                ('department', models.CharField(blank=True, max_length=128, verbose_name='部门')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='UserClusterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(blank=True, help_text='留空表示所有命名空间', max_length=128, verbose_name='命名空间')),
                ('resource_type', models.CharField(choices=[('*', '所有资源'), ('namespace', 'Namespace'), ('node', 'Node'), ('deployment', 'Deployment'), ('statefulset', 'StatefulSet'), ('daemonset', 'DaemonSet'), ('pod', 'Pod'), ('service', 'Service'), ('ingress', 'Ingress'), ('configmap', 'ConfigMap'), ('secret', 'Secret'), ('persistentvolumeclaim', 'PVC')], default='*', max_length=32, verbose_name='资源类型')),
                ('permission', models.CharField(choices=[('view', '查看'), ('edit', '编辑'), ('delete', '删除'), ('full', '完全控制')], default='view', max_length=16, verbose_name='权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='clusters.cluster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户集群权限',
                'verbose_name_plural': '用户集群权限',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'cluster', 'namespace', 'resource_type')},
            },
        ),
    ]
