# Generated by Django 6.0.3 on 2026-04-20 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clusters', '0002_cluster_prometheus_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userclusterpermission',
            options={'ordering': ['-created_at'], 'verbose_name': '用户集群权限(旧)', 'verbose_name_plural': '用户集群权限(旧)'},
        ),
        migrations.AlterField(
            model_name='userclusterpermission',
            name='namespace',
            field=models.CharField(blank=True, max_length=128, verbose_name='命名空间'),
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', '仪表盘'), ('cluster', '集群管理'), ('node', '节点管理'), ('namespace', '命名空间'), ('deployment', 'Deployment'), ('statefulset', 'StatefulSet'), ('daemonset', 'DaemonSet'), ('pod', 'Pod'), ('service', 'Service'), ('ingress', 'Ingress'), ('configmap', 'ConfigMap'), ('secret', 'Secret'), ('pvc', 'PVC')], max_length=32, verbose_name='模块')),
                ('permission', models.CharField(choices=[('view', '查看'), ('edit', '编辑')], default='view', max_length=16, verbose_name='权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='clusters.cluster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户模块权限',
                'verbose_name_plural': '用户模块权限',
                'ordering': ['user', 'cluster', 'module'],
                'unique_together': {('user', 'cluster', 'module')},
            },
        ),
    ]
