# Generated by Django 6.0.3 on 2026-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userclusterpermission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='姓名'),
        ),
    ]
