# Generated by Django 6.0.4 on 2026-04-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='集群名称')),
                ('display_name', models.CharField(blank=True, max_length=128, verbose_name='显示名称')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知')], default='unknown', max_length=16, verbose_name='状态')),
                ('k8s_version', models.CharField(blank=True, max_length=64, verbose_name='K8s 版本')),
                ('os_info', models.CharField(blank=True, max_length=256, verbose_name='系统信息')),
                ('api_server', models.CharField(blank=True, max_length=512, verbose_name='API Server')),
                ('node_count', models.IntegerField(default=0, verbose_name='节点数')),
                ('_kubeconfig_encrypted', models.BinaryField(verbose_name='Kubeconfig (加密)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '集群',
                'verbose_name_plural': '集群',
                'ordering': ['-created_at'],
            },
        ),
    ]
