# Generated by Django 6.0.4 on 2026-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='prometheus_url',
            field=models.CharField(blank=True, help_text='例如: http://prometheus.monitoring:9090', max_length=512, verbose_name='Prometheus 地址'),
        ),
    ]
