# Generated by Django 6.0.3 on 2026-04-21 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='K8sResourceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(db_index=True)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('namespace', models.CharField(db_index=True, default='', max_length=255)),
                ('data', models.JSONField()),
                ('synced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'k8s_resource_cache',
                'unique_together': {('cluster_id', 'resource_type', 'namespace')},
            },
        ),
    ]
